
#-----------------------------------------------------------------------

SLN_DIR   :=$(shell (cd ../../../../; pwd))

APP       := TestApp
TARGET    := ProxyServer
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += -I ../HelloServer
LIB       += 

#-----------------------------------------------------------------------

include ${SLN_DIR}/cpp/servant/makefile/makefile.tars

#-----------------------------------------------------------------------
