
#-----------------------------------------------------------------------

#TODO: SLN_DIR修改为Tars源码根目录，相对目录
SLN_DIR   :=$(shell (cd ../../../../; pwd))

APP       := DemoApp
TARGET    := DemoServer
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------

include ${SLN_DIR}/cpp/servant/makefile/makefile.tars

#-----------------------------------------------------------------------
