
#-----------------------------------------------------------------------

SLN_DIR   :=$(shell (cd ../../../../; pwd))

APP       := TestApp
TARGET    := testParallelCoro
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   +=
LIB       += 

#-----------------------------------------------------------------------

include ${SLN_DIR}/cpp/servant/makefile/makefile.tars

#-----------------------------------------------------------------------
