
#-----------------------------------------------------------------------

SLN_DIR   :=$(shell (cd ../../../../; pwd))

APP       := TestApp
TARGET    := Client
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += -I ../AServer
LIB       += 

#-----------------------------------------------------------------------

include ${SLN_DIR}/cpp/servant/makefile/makefile.tars

#-----------------------------------------------------------------------
