
#-----------------------------------------------------------------------

SLN_DIR   :=$(shell (cd ../../../../../; pwd))

APP       := TestApp
TARGET    := HelloAsyncClient
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += -I ..
LIB       += 

#-----------------------------------------------------------------------

include ${SLN_DIR}/cpp/servant/makefile/makefile.tars

#-----------------------------------------------------------------------
