
#-----------------------------------------------------------------------

SLN_DIR   :=$(shell (cd ../../../../; pwd))

APP       := HttpDemo
TARGET    := HttpClient
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------

include ${SLN_DIR}/cpp/servant/makefile/makefile.tars

#-----------------------------------------------------------------------
